### ISSUE TITLE
how to start in ubuntu?

### ISSUE THREAD

**Issue by Solomon2014** [nczempin/Turres-Monacorum#155]
how to start in ubuntu? what i need do to start this game in ubuntu?

**Comment by nczempin** [comment]
Which version of Ubuntu?

You need love2d 0.9.1; let me check which version comes with Ubuntu 16.04.

**Comment by nczempin** [comment]
Okay, so Ubuntu 15.04, 15.10, 16.04 use love2d 0.9.1: https://launchpad.net/ubuntu/+source/love

**Comment by nczempin** [comment]
so I'm guessing you'll need to install love, with something like
`sudo apt-get install love`
and then follow the instructions here: https://love2d.org/wiki/Getting_Started

**Comment by Solomon2014** [comment]
Hi, **nczempin**. Sorry please, i long time did not respond to your comments. You help me to run this game. I install love2d and follow the instructions. Thank you.
